### PR TITLE
Evaluate DynaFormModelElement as the last eligible case

### PR DESCRIPTION
**Pull request by Rapster**

### CODE REVIEW

**Comment by ova2** [comment]
Very good. Thanks for your effort!

**Comment by ova2** [comment]
By the way, Sebastien, should I add you as committer to PF Extensions? We have some inactiv members. I would remove inactive members and add you as committer. What do you think?

**Comment by Rapster** [comment]
I really appreciate that Oleg, indeed I'm working on a big project using Primefaces and lately, DynaForm saved us a lot of trouble from memory issues: this is why I created a few ticket. I hope I could do more in the future as I really like to involve myself in Primefaces. As I'm not a JSF expert, I still have to understand some basics and other stuff, I think it is more wise that I continue to make pull request and someone review the code, at some point, I hope I'll have enough skills to become a committer to PF Extensions.

**Comment by ova2** [comment]
Ok, all right.

By the way, I have planned to add this feature to DynaForm (responsive layout with DIVs instead table) https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/321 but didn't have interest then because changed my job and the new client doesn't use DynaForm :-) If you want, you can try to do this. Just FYI.

**Pull request merged**
