### PR TITLE
New: ThemeAccentColorResourceHandler

### PR DESCRIPTION
**Pull request by jepsar**
This allows you to easily modify the accent colors of the arya, saga and vela themes. Let me know what you think. Showcase documentation still needs to be added.

### CODE REVIEW

**Comment by melloware** [comment]
i don't see how global.css is used?

**Comment by jepsar** [comment]
Basically the accent colors in the theme are replaced with variables instead of static hex values.

0: general button color
1: hover
2: active
3: focus

**Comment by melloware** [comment]
cool with me

**Comment by jepsar** [comment]
Screenshot 2021-04-02 at 19 05 35

Used pink, so you cannot mis it is custom

**Comment by jepsar** [comment]
@melloware added documentation

**Comment by melloware** [comment]
Excellent!  Safe to merge .

**Comment by melloware** [comment]
Hey I checked this out now.  Works great but can you fix the colors. The Dark Pink is too harsh.  Maybe just change the color for one of the themes not all 3 so we show our components in the PF defaults?

**Comment by jepsar** [comment]
> The Dark Pink is too harsh

😂  .. I'll change it

**Comment by jepsar** [comment]
Screenshot 2021-04-03 at 14 54 21

**Comment by melloware** [comment]
Much better!

**Pull request merged**
