### PR TITLE
Fix 534: Added FAB component

### PR DESCRIPTION
**Pull request by jepsar**
This should do for a first version. Showcase will follow. Example use:

```
<pe:fab style="background: red">
  <p:menuitem value="Test test"
              icon="pi pi-key"
              url="/test"/>
  <p:menuitem value="Nog een item"
              icon="pi pi-star"
              action="#{myBean.setString('fiets')}"
              style="background: green"/>
</pe:fab>
```

### CODE REVIEW

**Review by melloware — APPROVED** [review]
Really nice work!

**Comment by jepsar** [comment]
@melloware Can you take care of minifying the resources please?

**Comment by melloware** [comment]
Yep I will minify it.

**Comment by melloware** [comment]
OK CSS and JS minified.

**Pull request merged**
