### PR TITLE
KeyFilter improvement: InputRegEx to have regEx on the whole text

### PR DESCRIPTION
**Pull request by Julienng**
I create a new Parameter to add regEx like `/^[0-9]{0,3}((\\.|,)[0-9]{0,6}|)$/`.
- Parameter inputRegEx.
- Function inputFilter based on event Jquery 'input'.

### CODE REVIEW

**Comment by ova2** [comment]
Thomas, is it ok for you? Can we approve the pull request?

**Comment by tandraschko** [comment]
Thanks for the pull request.
Would you please move the logic from $.fn.inputFilter to the 1-keyfilter.js file?
Thats because 0-jquery.keyfilter.js is the jquery plugin and we possible overwrite your changes if we update it in the future.

**Comment by Julienng** [comment]
What did you mean ? Like move my logic into a function in `keyFilter` and pass it like a callback into `inputFilter` ?

**Comment by tandraschko** [comment]
i would remove the jquery function and directly apply the .on the inputfield.

input.inputFilter(this.cfg.inputRegEx);

->

input.on('input', function(e) {.....});

**Comment by Julienng** [comment]
Ok, I would do it.

**Comment by Julienng** [comment]
I doesn't have enough time last week. It's uglier than before but work as expected.

**Comment by tandraschko** [comment]
Looks good from my perspective. i will merge it :)

**Comment by Julienng** [comment]
Good news. :smile:  Just in case: every regEx into inputRegEx have to start with `^` and finish with `$` to match the complete string.

**Pull request merged**
