### PR TITLE
Fix #303: LightSwitch switch event

### LINKED ISSUE #303: LightSwitch: Add switch event
.. so you can update components on switch. For example, on the showcase the theme selector is showing an outdated theme on switch.

### PR DESCRIPTION
**Pull request by jepsar**
Fix #303

This adds the event, but does not (yet) fix the bug we've found with the non-event variant.

### CODE REVIEW

**Comment by jepsar** [comment]
Not perfect, but it's working. Can be tested by removing `<p:ajax update="themeSelectMenu"/>`.

**Review by melloware — APPROVED** [review]
Nice changes.  I figured it had to be in its own form that is a good idea.

**Comment by melloware** [comment]
Working well for me.

**Comment by jepsar** [comment]
> Working well for me.

Did you also check without `<p:ajax update="themeSelectMenu"/>`?

**Comment by jepsar** [comment]
To properly fix this, I think we need to be able to bypass

https://github.com/primefaces/primefaces/blob/47a1f00dc3f2be3a66e37e75330eba65a9e380d8/src/main/java/org/primefaces/context/PrimePartialResponseWriter.java#L268-L295

**Comment by melloware** [comment]
I did not try it without the AJAX.   Let me investigate today and see if I come to the same conclusion.

**Pull request merged**
