### PR TITLE
Fix 723 Cleaned up TimePicker styling

### LINKED ISSUE #723: TimePicker: doesn't look okay with modern themes
Go to https://www.primefaces.org/showcase-ext/sections/timePicker/basicUsage.jsf and switch to nova-light for example.

### PR DESCRIPTION
**Pull request by jepsar**
This should fix https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/723

It's looking good on my MacBook with Chrome. We might want to test with some other browsers. I think we are alright though, since the majority of the styling is inherited from existing components (like spinner and input group)

### CODE REVIEW

**Comment by melloware** [comment]
I will check this out on Edge, IE and Firefox and let you know how it looks!

**Comment by melloware** [comment]
This looks good.  There are still a few issues though...

1. Look at the Spinners in Nova-Light and Nova-Dark.
image

2. The popup styling is off in the premium themes.  
**Good (Omega):**
image

**Bad (Nova-Dark):**
image

**Review by melloware — CHANGES_REQUESTED** [review]
See comment in conversation.

**Comment by jepsar** [comment]
The customization input is an issue with the showcase (the with of that input is hardcoded there). We might want to add 10 to 15px there.

What browser gave you issues with the spinners?

What is wrong with the popup (other than the button style)?

**Comment by melloware** [comment]
I was testing in Chrome and Firefox.  Didn't try IE and Edge yet.  I am on Windows.

As for the popup doesn't it look really naked compared to Omega? No borders around dates etc?  Maybe its supposed to be that way it just looks awfully plain and the buttons are not styled.

image

vs Omega...

image

**Comment by melloware** [comment]
OK the good news is its working in Firefox, Chrome, IE and Edge.  But the the same spinner and popup rendering is consistent in all 4 browsers.

**Comment by jepsar** [comment]
> As for the popup doesn't it look really naked compared to Omega?

I tried to apply very mild styling and to keep it in line with, for example, `p:calendar`

> But the the same spinner and popup rendering is consistent in all 4 browsers.

Okay, I'll look in to that.

**Comment by jepsar** [comment]
@melloware can you please test again? Please note that I've also submitted a change to the showcase: https://github.com/primefaces-extensions/showcase/pull/22

**Comment by melloware** [comment]
I will check it out!

**Pull request merged**
