### PR TITLE
[Perf] No need to keep looping once caseToRender has been set

### PR DESCRIPTION
**Pull request by Rapster**
Fix for #369

### CODE REVIEW

**Comment by tandraschko** [comment]
the PR looks fine but please create a issue for tracking.

**Comment by Rapster** [comment]
Don't have access to the "Issues" menu item :/

**Comment by tandraschko** [comment]
It's here: https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues

**Comment by Rapster** [comment]
Done: #369

**Comment by Rapster** [comment]
By the way, is there any performance added-value by using switch rather than consecutive `ui:fragment`

**Comment by tandraschko** [comment]
Don't think so.
Applied - thanks for the PR!

**Pull request merged**
