### PR TITLE
FIXME for various XSS vulnerabilities in github component

### PR DESCRIPTION
**Pull request by cnsgithub**
Not sure how to ask questions (no gitter room) or report issues. Are there any contribution guidelines for these PrimeFaces incubator components?

I'd have already provided a PR if it was clear where to place some common functionality like escaping HTML in javascript. primefaces-extensions.source.js? core.js? Just copy&paste it to all available versions? Then use it in all github.source.js versions?

### CODE REVIEW

**Comment by tandraschko** [comment]
-> GitterRoom: https://gitter.im/primefaces-extensions

**Comment by cnsgithub** [comment]
Don't like monologues very much. :beer: 

image

**Comment by melloware** [comment]
Hmm I am in that gitter room right now.  Let me invite you.

**Comment by melloware** [comment]
@cnsgithub When I try and add you to the the Extensions gitter it says "forbidden" when I try and add your user.

**Comment by cnsgithub** [comment]
Maybe too evil? :cry:

**Comment by melloware** [comment]
As for your question all available PrimeFaces JS and escaping methods are available to use in PFE.  In fact we try and use as much from PF as we can so we don't have to copy and paste code.

So our guidelines are basically "Make it as close to PF as possible" so if a component ever gets promoted it will be an easier time to move it to PF.

**Comment by cnsgithub** [comment]
On which PrimeFaces version the extensions in master branch are based currently? For example, I am missing `escapeHTML `function from PrimeFaces `core.js`.

**Comment by melloware** [comment]
So right now the current branch is based on PF Community 6.2.

Before 6.3.RC1 gets created then we move to 6.3 and update PFE I have this open ticket: https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/569

**Comment by tandraschko** [comment]
(i would start this month with it, RC1 will be released in december)

**Comment by cnsgithub** [comment]
Procedure:
1. Introduce `escapeHTML `function in PFE `core.js`.
2. Use newly introduced function in `0-jquery.github.js`.
3. Add task to the TODO list so that the function can be reverted after switching to PF 6.3: primefaces-extensions/primefaces-extensions.github.com#569

**Comment by melloware** [comment]
@cnsgithub Let me cut a 6.2.X of PFE which will be the last 6.2 version and then I can bump /master to be on PF 6.3-SNAPSHOT so we can start converting to 6.3.  I will let you know when I make the changes should be this week sometime

**Comment by cnsgithub** [comment]
Oops, just provided a PR: https://github.com/primefaces-extensions/core/pull/62.

It's up to you if you want to merge it before or after the PF rebase. Adjusting the PR for PF 6.3 should be straightforward: just turn calls to `PrimeFacesExt.escapeHTML `to `PrimeFaces.escapeHTML` and drop the first one.

**Pull request closed without merging**
