### PR TITLE
Fix 765 input phone dependency

### LINKED ISSUE #765: InputPhone causes NoClassDefFoundError on deployment due to missing com.googlecode.libphonenumber
Glassfish 5.1 log:
Source Document: jar:file:/home/..path to../domains/domain1/applications/MyApp/WEB-INF/lib/primefaces-extensions-8.0.jar!/META-INF/faces-config.xml
  Cause: Class 'org.primefaces.extensions.component.inputphone.InputPhoneRenderer' is missing a runtime dependency: java.lang.NoClassDefFoundError: com/google/i18n/phonenumbers/NumberParseException

I'm not using inputphone at all

### PR DESCRIPTION
**Pull request by jepsar**
Fix https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/765

### CODE REVIEW

**Review by melloware — APPROVED** [review]
This is a great fix.   I will update the master pom to make libPhonNumber optional so people not using InputPhone don't have to have the dependency added to their WAR automatically.

**Comment by jepsar** [comment]
Then we need to update the documentation as well. As people might already be using this input, that would be a breaking change.

**Comment by melloware** [comment]
Yep i will update the wiki.

**Comment by melloware** [comment]
Docs updated: https://github.com/primefaces-extensions/primefaces-extensions.github.com/wiki/Getting-Started

**Pull request merged**
