### PR TITLE
Fix #457: Scaffolding

### LINKED ISSUE #457: New component: Scaffolding
To work with skeletons more easily.

Example:

```xhtml
<pe:scaffolding ready="#{not empty scaffoldingController.data}" id="scaffolding"
                loader="#{scaffoldingController.fetchData(2000)}">
    <f:facet name="loading">
        <p:skeleton width="3rem" height="3rem" shape="circle"/>
    </f:facet>
    <f:facet name="ready">
        <p:avatar label="#{scaffoldingController.data}" size="large" shape="circle" />
    </f:facet>
</pe:scaffolding>
```

See also https://discord.com/channels/787967399105134612/787969344768311296/859078890022371348

### PR DESCRIPTION
**Pull request by jepsar**
Fix #457 

```xhtml
<pe:scaffolding ready="#{not empty scaffoldingController.data}" id="scaffolding"
                loader="#{scaffoldingController.fetchData(2000)}">
    <f:facet name="loading">
        <p:skeleton width="3rem" height="3rem" shape="circle"/>
    </f:facet>
    <f:facet name="ready">
        <p:avatar label="#{scaffoldingController.data}" size="large" shape="circle" />
    </f:facet>
</pe:scaffolding>
```

cc @stolp

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Looking pretty good to me.  @stolp if you don't have any suggestions I will merge this!

**Comment by stolp** [comment]
This looks good to me, great work!

I just have a general question regarding the taglib attributes. Is there a specific order we enforce here (e.g. alphabetic?)?

**Comment by FlipWarthog** [comment]
@stolp @melloware w/r/t ordering in the taglib, does it matter since it's XML? If so, it might be worth standardizing a pattern, e.g. common(id, rendered, style), then whatever is specific to the component, then any Client stuff (onclick, onblur).

**Comment by jepsar** [comment]
I usually put the common attributes first, and then add attributes chronologically.

**Comment by melloware** [comment]
I usually follow @jepsar pattern as well.  Since its XML there is no good way to sort them etc with any tool without parsing it.  Luckily the order doesn't matter and the IDE's all know how to parse and read it.

**Pull request merged**
