### PR TITLE
New Component: Fuzzy Search

### PR DESCRIPTION
**Pull request by aripddev**
Hi @melloware I created a new PR from scratch. Now finally I can make search and get results. The only problem remained is when I click any result, I get NPE.
I think it is because `Object submittedValue` parameter in `getConvertedValue` method. It is always null. I couldn't figure out why. Can you give me a hint to solve it?

```java
@Override
public Object getConvertedValue(FacesContext context, UIComponent component, Object submittedValue) throws ConverterException {
  return ComponentUtils.getConvertedValue(context, component, (String) submittedValue);
}
```

### CODE REVIEW

**Comment by melloware** [comment]
Thanks for the new PR makes it easier on us.  Anyway I don't think you want to override getConvertedValue I think you want to override the entire `decode` method since you are delegating to SelectOne which is not what you want.  I think you want a custom `decode`.

```java
@Override
    public void decode(FacesContext context, UIComponent component) {
        UISelectOne selectOne = (UISelectOne) component;
        if (!shouldDecode(selectOne)) {
            return;
        }

        String clientId = getSubmitParam(context, selectOne);
        Map<String, String> params = context.getExternalContext().getRequestParameterMap();

        String submittedValue = params.containsKey(clientId) ? params.get(clientId) : "";
        List<String> validSubmittedValues = validateSubmittedValues(context, selectOne, (Object[]) getValues(selectOne), submittedValue);
        selectOne.setSubmittedValue(validSubmittedValues.isEmpty() || validSubmittedValues.contains(submittedValue)
                ? submittedValue
                : validSubmittedValues.get(0));

        decodeBehaviors(context, selectOne);
    }
```

**Comment by aripddev** [comment]
Thanks @melloware , now it's working

**Comment by melloware** [comment]
Are you satisfied is this ready to be merged?

**Comment by aripddev** [comment]
Yes, please

**Pull request merged**
