### PR TITLE
Scaffolding: Added check, resources and load data on page load

### LINKED ISSUE #472: Scaffolding: renders ready twice without MOVE_SCRIPTS_TO_BOTTOM

### PR DESCRIPTION
**Pull request by jepsar**

### CODE REVIEW

**Comment by melloware** [comment]
Do you want to merge this or keep it open for the other issue you are working on?

**Comment by jepsar** [comment]
Let's keep it open and I'll use it for the other fixes as well

**Comment by jepsar** [comment]
@melloware this is working with and without `primefaces.MOVE_SCRIPTS_TO_BOTTOM`

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Looks good!  Feel free to merge when you are ready!

**Pull request merged**
