### PR TITLE
add moono-lisa skin to documentation

### PR DESCRIPTION
**Pull request by jxmai**
snapshot1

### CODE REVIEW

**Comment by melloware** [comment]
Hey do you mind testing and reviewing the fix to CKEditor I made here the other day?

https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/424

**Comment by jxmai** [comment]
No problem, I can review the changes and provide feedback later.

**Comment by melloware** [comment]
Also when I run the showcase I get this warning at the command line.

> 
> Dec 10, 2016 10:11:35 AM com.sun.faces.context.ExternalContextImpl getMimeType
> WARNING: JSF1091: No mime type could be found for file ckeditor/plugins/copyformatting/.  To resolve this, add a mime-type mapping to the applications web.xml.

Which is weird and I wouldn't know what mime type to even add. because usually its a file like "hello.woff" and it doesn't know the WOFF extension.

**Comment by melloware** [comment]
Also in Chrome Console window I see this...

> VM4506:85 Resource interpreted as Stylesheet but transferred with MIME type text/plain: "http://localhost:8080/primeext-showcase/javax.faces.resource/ckeditor/plugi…wsc/.jsf?ln=primefaces-extensions&v=6.1.0-SNAPSHOTskins/moono-lisa/wsc.css".

**Comment by tandraschko** [comment]
If a file " ckeditor/plugins/copyformatting" is requested, than the CKEditor plugin likely doesn't use the internal CKEditor.getResource method, which we overwrite to resolve it to JSF resource urls

**Comment by jxmai** [comment]
There are three warnings. All three of them are from the plugin directory, but the css itself looks OK and I am not sure what url should be overwritten

For example, 

>VM1403:85 Resource interpreted as Stylesheet but transferred with MIME type text/plain: "http://localhost:8080/showcase/javax.faces.resource/ckeditor/plugins/scayt/.jsf?ln=primefaces-extensions&v=6.1.0-SNAPSHOTskins/moono-lisa/scayt.css".

The scayt.css looks like this:

```css
.scayt-lang-list > div
{
    padding-bottom: 6px !important;
}

.scayt-lang-list > div input
{
    margin-right: 4px;
}

#scayt_about_
{
    width: 190px;
    margin: 30px auto 0 auto;
}

.cke_dialog_contents_body div[name=dictionaries] .cke_dialog_ui_hbox_last > a.cke_dialog_ui_button
{
    margin-top: 0;
}

```

Am I missing something ? Where should the changes be done in order to remove the warnings?

**Comment by tandraschko** [comment]
We overwrite the resource loading mechanism of CKEditor to remap the resources to JSF urls. Check the widget.js and CKEDITOR_GETURL method.

The resource url your posted ("http://localhost:8080/showcase/javax.faces.resource/ckeditor/plugins/scayt/.jsf?ln=primefaces-extensions&v=6.1.0-SNAPSHOTskins/moono-lisa/scayt.css") is exactly that problem.

The plugin requests e.g. the directory:
CKEDITOR_GETURL('/plugins/myplugindirectory')
and later the plugin just appends the resource:
var resource dir + skins/moono-lisa/scayt.css;
But the plugin must use there also the CKEDITOR_GETURL.

Check out my ticket and PR, i fixed many in the past of them:
https://dev.ckeditor.com/ticket/10804
https://github.com/tandraschko/ckeditor-dev/commits/master

If something happens, i first add some console.log to CKEDITOR_GETURL, to check what happens.
After that i check the ckeditor source and fix it in our ResourceModifier. Thereis already a hack for the smiley plugin as CKEditor rejected my PR.

**Comment by jxmai** [comment]
Thanks for the inside information. Now I am able to remove one of the warnings related to the copyFormatting. The `plugin.js` for copyFormatting is merged into `ckeditor.js` in production in minified form. It  did create some trouble for me to trace.  The changes need to be done in `ckeditor.js`. As a first step, I only manually added the wrapper (I will think of a way to modify `ResourceModifier.java` later so that the changes can be applied to the future update).

The following is the result so far (as a LOG)

CKEditor.js
```js
...
CKEDITOR.plugins.add("copyformatting", {
            lang: "en",
            icons: "copyformatting",
            hidpi: !0,
            init: function(a) {
                var b = CKEDITOR.plugins.copyformatting;
                b._addScreenReaderContainer();
                r || (CKEDITOR.document.appendStyleSheet(CKEDITOR.getUrl(this.path + "styles/copyformatting.css")),
                    r = !0);
                a.addContentsCss && a.addContentsCss(CKEDITOR.getUrl(this.path + "styles/copyformatting.css"));
                a.copyFormatting = new b.state(a);
                a.addCommand("copyFormatting", b.commands.copyFormatting);
                a.addCommand("applyFormatting", b.commands.applyFormatting);
                a.ui.addButton("CopyFormatting", {
                    label: a.lang.copyformatting.label,
                    command: "copyFormatting",
                    toolbar: "cleanup,0"
                });
...
```

copyFormatting.css

```css
...
.cke_copyformatting_disabled,
.cke_copyformatting_disabled a,
.cke_copyformatting_disabled .cke_editable {
	cursor: url("#{resource['primefaces-extensions:../cursors/cursor-disabled.svg']}") 12 1, auto;
}
...
```

So far

snapshot1

--- 
- [x] fix warning from copy formatting with PR: https://github.com/primefaces-extensions/resources-ckeditor/pull/10
- [x] fix warning from wsc.css with PR: https://github.com/primefaces-extensions/resources-ckeditor/pull/11
- [x] fix warning from scayt.css with PR: https://github.com/primefaces-extensions/resources-ckeditor/pull/11

**Pull request merged**
