### PR TITLE
Implements #537 Add support for Monaco diff editor

### LINKED ISSUE #537: MonacoEditor: Add diff editor
Can diff editor be added for monaco editor.
thanks.

### PR DESCRIPTION
**Pull request by blutorange**
Closes #537 

* Two new components: <pe:monacoDiffEditor/> and <pe:monacoDiffEditorFramed />
* The component API (XHTML properties) and client-side API (widget methods) are mostly identical to the code (non-diff) editor. There are a few new properties to control the behavior of the original editor (the one to the left of the diff editor), such as "originalDisabled" or "PrimeFaces.widget.monacoDiffEditor.getOriginalValue()"
* The "value" property must be an instance of "MonacoDiffEditorModel", which is essentially an ordered pair of two strings.
* For each showcase example, there's now a new example with the diff editor.
* Fixed a bug with the generation of locales, some i18n keys were missing.
* Some other minor bugs and inconsistencies were fixed, corrected some spelling errors and dead links.

---

I tested it against the showcase, but would be great if somebody could run the showcase too and see if you spot any errors.

### CODE REVIEW

**Comment by melloware** [comment]
I will test tomorrow when I am in the office

**Comment by melloware** [comment]
I did a fresh pull of your branch and get this error on `mvn clean install`

```
 --- frontend-maven-plugin:1.12.1:npm (generate-locales) @ resources-monacoeditor ---
[INFO] Running 'npm run generate-locales' in C:\Temp\monaco-diff\monacoeditor\src\main\js
[INFO]
[INFO] > primefaces-extensions-resources-monacoeditor@1.0.0 generate-locales
[INFO] > node src/scripts/generateLocales.js
[INFO]
[INFO] C:\Temp\monaco-diff\monacoeditor\src\main\js\node_modules\mkdirp\lib\path-arg.js:20
[INFO]       throw Object.assign(new Error('Illegal characters in path.'), {
[INFO]                           ^
[INFO]
[INFO] Error: Illegal characters in path.
[INFO]     at pathArg (C:\Temp\monaco-diff\monacoeditor\src\main\js\node_modules\mkdirp\lib\path-arg.js:20:27)
[INFO]     at Function.mkdirp.native (C:\Temp\monaco-diff\monacoeditor\src\main\js\node_modules\mkdirp\index.js:26:46)
[INFO]     at main (file:///C:/Temp/monaco-diff/monacoeditor/src/main/js/src/scripts/generateLocales.js:266:18)
[INFO]     at file:///C:/Temp/monaco-diff/monacoeditor/src/main/js/src/scripts/generateLocales.js:296:1
[INFO]     at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
[INFO]     at async Promise.all (index 0)
[INFO]     at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
[INFO]     at async loadESM (node:internal/process/esm_loader:88:5)
[INFO]     at async handleMainPromise (node:internal/modules/run_main:65:12) {
[INFO]   path: 'C:\\C:\\Temp\\monaco-diff\\monacoeditor\\target\\git',
[INFO]   code: 'EINVAL'
[INFO] }
```

**Comment by blutorange** [comment]
> [INFO]   path: 'C:\\C:\\Temp\\monaco-diff\\monacoeditor\\target\\git',
 
The `C:\\C:\\` is probably the issue. Not sure where that comes from, may have to try it on a windows system

**Comment by blutorange** [comment]
Alright, hope it's fixed, if you could try again

ps, I wonder if the gitlab workflow could do without running the PrimeFaces tests (-DskipTests / -DskipITs)? Since I suppose we only want to check if it builds against the current snapshot? https://github.com/primefaces-extensions/primefaces-extensions/blob/master/.github/workflows/build.yml#L32

**Comment by melloware** [comment]
works!

**Comment by melloware** [comment]
Is it safe for me to merge this?

**Comment by blutorange** [comment]
Yeah if it compiles for you too and you can run the showcase, it's fine now.

**Comment by melloware** [comment]
I do have one question though from looking at your code.  So if you pass the Monaco Editor 2 strings it handles doing all the differencing and display in the JS code ?  If so that is AWESOME!  Let me know.

**Comment by blutorange** [comment]
Exactly, you pass `<p:monacoDiffEditor value="bean.value" />` a `MonacoDiffEditorModel`, which is just a POJO with two strings. Rest is done by Monaco editor.

**Comment by melloware** [comment]
amazing!

**Pull request merged**
