### PR TITLE
Sheet: ConcurrentHashMap instead of HashMap

### LINKED ISSUE #851: Sheet: java.util.ConcurrentModificationException when SessionScoped and fast updates
### Describe the bug

When using a sheet SessionScoped working fast `entries.remove();` in Sheet#validate on line 725 throws a java.util.ConcurrentModificationException.

Using `Collections.synchronizedMap` instead of `new HashMap<>();` will I think fix the problem.

I try to do a PR

### Reproducer

no

### Expected behavior

When working fast and SessionScoped no ConcurrentModificationException is thrown

### PrimeFaces Extensions version

11.0.0

### JSF implementation

Mojarra

### JSF version

2.3

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by eduarddrenth**

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Nice if you have tested this fixes your issue I am happy to merge it?

**Comment by eduarddrenth** [comment]
I'll test in a running app soon

Op za 4 jun. 2022 14:43 schreef Melloware ***@***.***>:

**Comment by eduarddrenth** [comment]
unfortunately testing is blocked by the payara deel scanning issue

Op za 4 jun. 2022 14:51 schreef Eduard Drenth ***@***.***>:

**Comment by melloware** [comment]
Just add Monaco to your Pom.xml to fix that issue temporarily.

**Comment by eduarddrenth** [comment]
Fixes this issue, but allas silently loosing a lot of data (see #814) now. Do some more testing

**Comment by eduarddrenth** [comment]
Workaround for now:

`<p:ajaxExceptionHandler type="java.util.ConcurrentModificationException" onexception="$('#buttons\\:ververs').click();alert('Changes not recorded! Working a bit slower may help.');" update="exceptionDialog"/>`

**Comment by jepsar** [comment]
Never tried this, but can't block UI be used here?

**Comment by eduarddrenth** [comment]
This pr fixes the issue and causes no loss of data

**Comment by eduarddrenth** [comment]
This PR introduced an NPE on `Sheet.setLocalValue(Sheet.java:294)`, ConcurrentHashMap does not allow null for value:
```
    final V putVal(K key, V value, boolean onlyIfAbsent) {
        if (key == null || value == null) throw new NullPointerException();
```
I'll see what should/can be done

**Pull request merged**
