### PR TITLE
Fix #271 InputPhone: should respect theme colors

### LINKED ISSUE #271: InputPhone: should respect theme colors
Screen Shot 2021-01-23 at 15 47 40

### PR DESCRIPTION
**Pull request by jepsar**
Fix #271

Screen Shot 2021-01-23 at 16 30 00

Screen Shot 2021-01-23 at 16 30 19

### CODE REVIEW

**Comment by jepsar** [comment]
@melloware do you have any idea how I could style the outline on the dropdown button? I thought it was done with the outline property, but it's not...

**Comment by melloware** [comment]
Let me take a look

**Comment by melloware** [comment]
I am going to merge this so I can run it locally.

**Comment by melloware** [comment]
Ok I am a little stumped.  I don't see anything styling that border when you click on the flag dropdown.  Nothing in the Inspector is showing that as bordered!

**Comment by jepsar** [comment]
Okay.. maybe something Chrome or Mac specific..

**Pull request merged**
