### PR TITLE
Added maven.config

### PR DESCRIPTION
**Pull request by jepsar**
This allows you to only having to change the version at a single location

### CODE REVIEW

**Comment by melloware** [comment]
nice but this does not affect the Deploy plugin right?

**Comment by tandraschko** [comment]
i dont really like it
never seen a project which uses the pattern (PF or many Apache projects)

**Comment by tandraschko** [comment]
and you can change all versions via single command: mvn versions:set

**Comment by melloware** [comment]
Here is what I do for PrimeSelenium...
```
Update pom.xml to new version e.g 8.0.2
Run mvn -N versions:update-child-modules -DgenerateBackupPoms=false to update all child modules versions
Commit and push the changes to GitHub
In GitHub create a new Release titled 8.0.2 to tag this release
Run mvn clean deploy -Prelease to push to Maven Central
```

**Comment by tandraschko** [comment]
mvn versions:set -DnewVersion=10.0-SNAPSHOT 

will change it in the root pom and update all submodules

**Comment by melloware** [comment]
Awesome let me go update my notes.  I have always done the update-child-modules but i like yours better.

**Comment by jepsar** [comment]
> and you can change all versions via single command: mvn versions:set

Ha, didn't know that. Cool!

**Comment by melloware** [comment]
I updated the Release instructions on the README.MD of this project.

**Pull request closed without merging**
