### PR TITLE
Use PrimeFacesExt.locales for i18n

### LINKED ISSUE #707: TimeAgo: Short flashing display of date string on page load and Ajax update
I am using Primefaces Extensions 7.0.1 with simple p:timeAgo instance like the following:
```
<pe:timeAgo id="createdTime"
      value="#{bean.created}" titlePattern="#{pageHandler.localizedDatePattern}" />
```
Upon page load or when the containing form is updated via an Ajax submit, I am noticing a small flicker. It looks like that the date string from the title is shortly inserted before the correct timeAgo text is shown. This is very irritating.

Is anybody else experiencing this as well?

### PR DESCRIPTION
**Pull request by jepsar**
@melloware this should fix https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/707 and makes this component to be in line with https://github.com/primefaces-extensions/primefaces-extensions.github.com/wiki/PrimeFaces-Extensions-Locales

Let me know what you think. If you merge this I'll also update the showcase.

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Good PR!

**Comment by stolp** [comment]
Great, thanks a lot!

What would I need to build to test this? Is building primefaces-extensions trunk enough?

**Comment by melloware** [comment]
Yep just do "mvn clean install" of the Master POM and then this Core project.

**Comment by stolp** [comment]
Sorry, I get the following error after replacing primfaces-extensions 7.0.2 with 7.0.3-SNAPSHOT (build from current source) in my application using pe:timeAgo in the Javascript console:

`timeago.js.seam?ln=primefaces-extensions&loc=&v=7.0.3-SNAPSHOT:77 Uncaught TypeError: Cannot read property 'prefixAgo' of undefined
    at Function.inWords (timeago.js.seam?ln=primefaces-extensions&loc=&v=7.0.3-SNAPSHOT:77)
    at inWords (timeago.js.seam?ln=primefaces-extensions&loc=&v=7.0.3-SNAPSHOT:222)
    at HTMLTimeElement.refresh (timeago.js.seam?ln=primefaces-extensions&loc=&v=7.0.3-SNAPSHOT:197)
    at i (jquery.js.seam?ln=primefaces&loc=&v=7.0.7:2)
    at HTMLTimeElement.init (timeago.js.seam?ln=primefaces-extensions&loc=&v=7.0.3-SNAPSHOT:145)
    at HTMLTimeElement.<anonymous> (timeago.js.seam?ln=primefaces-extensions&loc=&v=7.0.3-SNAPSHOT:178)
    at Function.each (jquery.js.seam?ln=primefaces&loc=&v=7.0.7:2)
    at k.fn.init.each (jquery.js.seam?ln=primefaces&loc=&v=7.0.7:2)
    at k.fn.init.$.fn.timeago (timeago.js.seam?ln=primefaces-extensions&loc=&v=7.0.3-SNAPSHOT:177)
    at c.init (timeago.js.seam?ln=primefaces-extensions&loc=&v=7.0.3-SNAPSHOT:255)
inWords @ timeago.js.seam?ln=primefaces-extensions&loc=&v=7.0.3-SNAPSHOT:77
inWords @ timeago.js.seam?ln=primefaces-extensions&loc=&v=7.0.3-SNAPSHOT:222
refresh @ timeago.js.seam?ln=primefaces-extensions&loc=&v=7.0.3-SNAPSHOT:197
i @ jquery.js.seam?ln=primefaces&loc=&v=7.0.7:2
init @ timeago.js.seam?ln=primefaces-extensions&loc=&v=7.0.3-SNAPSHOT:145
(anonymous) @ timeago.js.seam?ln=primefaces-extensions&loc=&v=7.0.3-SNAPSHOT:178
each @ jquery.js.seam?ln=primefaces&loc=&v=7.0.7:2
each @ jquery.js.seam?ln=primefaces&loc=&v=7.0.7:2
$.fn.timeago @ timeago.js.seam?ln=primefaces-extensions&loc=&v=7.0.3-SNAPSHOT:177
init @ timeago.js.seam?ln=primefaces-extensions&loc=&v=7.0.3-SNAPSHOT:255
e.<computed> @ core.js.seam?ln=primefaces&loc=&v=7.0.7:6
c @ core.js.seam?ln=primefaces&loc=&v=7.0.7:6
createWidget @ core.js.seam?ln=primefaces&loc=&v=7.0.7:1
cw @ core.js.seam?ln=primefaces&loc=&v=7.0.7:1
(anonymous) @ projects.seam?conversationId=4:131`

Did I miss something?

**Comment by jepsar** [comment]
You'll need to provide the translation yourself now (as with `TimePicker`). I still need to update the documentation / showcase on this change. This is how I tested it:

```
<script>
  PrimeFacesExt.locales.TimeAgo['nl'] = {
	prefixAgo: null,
	prefixFromNow: "over",
	suffixAgo: "geleden",
	suffixFromNow: null,
	seconds: "minder dan een minuut",
	minute: "ongeveer een minuut",
	minutes: "%d minuten",
	hour: "ongeveer een uur",
	hours: "ongeveer %d uur",
	day: "een dag",
	days: "%d dagen",
	month: "ongeveer een maand",
	months: "%d maanden",
	year: "ongeveer een jaar",
	years: "%d jaar",
	wordSeparator: " ",
	numbers: []
  }
</script>

<pe:timeAgo value="#{now}" locale="nl"/>
```

To copy / paste translations, have a look at https://github.com/rmm5t/jquery-timeago/tree/master/locales

**Comment by stolp** [comment]
This makes totally sense, thanks for the hint.

I can gladly confirm that this is working fine and that the flicker is now completely gone on all browser I tested (Brave, Chrome, Firefox, Edge, IE).

@jepsar, @melloware : Thank you very much for fixing this!

**Comment by jepsar** [comment]
> I can gladly confirm that this is working fine and that the flicker is now completely gone on all browser I tested (Brave, Chrome, Firefox, Edge, IE).

Thanks for testing and letting us know.

**Pull request merged**
